oS.Init({PName:[oPeashooter,oSunFlower,oCherryBomb,oWallNut,oPotatoMine,oSnowPea,oChomper,oRepeater,oPuffShroom,oSunShroom,oFumeShroom,oGraveBuster,oHypnoShroom,oScaredyShroom,oIceShroom,oDoomShroom,oLilyPad,oSquash,oThreepeater,oTangleKelp,oJalapeno,oSpikeweed,oTorchwood,oTallNut,oSeaShroom,oPlantern,oCactus,oBlover,oSplitPea,oStarfruit,oPumpkinHead,oFlowerPot,oCoffeeBean,oGarlic,oGatlingPea,oGloomShroom,oTwinSunflower,oSpikerock],ZName:[oZombie,oZombie2,oZombie3,oPoleVaultingZombie,oNewspaperZombie,oScreenDoorZombie,oFootballZombie,oDancingZombie,oBackupDancer,oZomboni,oImp,oJackinTheBoxZombie,oBalloonZombie],PicArr:["images/interface/background1.jpg"],backgroundImage:"images/interface/background1.jpg",CanSelectCard:1,SunNum:9990,LevelName:"小游戏：假·绝望",LvlEName:"jiajuewang",LargeWaveFlag:{10:$("imgFlag1")},StartGameMusic:"Ultimate battle"},{AZ:[[oZombie,5,10],[oZombie2,5,10],[oZombie3,5,10],[oPoleVaultingZombie,5,10],[oNewspaperZombie,5,10],[oScreenDoorZombie,5,10],[oFootballZombie,5,10],[oDancingZombie,5,10],[oBackupDancer,5,10],[oZomboni,5,10],[oImp,5,10],[oJackinTheBoxZombie,5,10],
[oBalloonZombie,5,10]],FlagNum:10,FlagToSumNum:{a1:[3,5,9],a2:[0,0,0,8900]},FlagToMonitor:{10:[ShowFinalWave,0]}});
oPeashooter.prototype.SunNum=0,
oSunFlower.prototype.SunNum=0,
oCherryBomb.prototype.SunNum=0,
oWallNut.prototype.SunNum=0,
oPotatoMine.prototype.SunNum=0,
oSnowPea.prototype.SunNum=0,
 oChomper.prototype.SunNum=0,
 oRepeater.prototype.SunNum=0,
 oPuffShroom.prototype.SunNum=0,
 oSunShroom.prototype.SunNum=0,
oFumeShroom.prototype.SunNum=0,
oGraveBuster.prototype.SunNum=0,
oHypnoShroom.prototype.SunNum=0,
oScaredyShroom.prototype.SunNum=0,
oIceShroom.prototype.SunNum=0,
oDoomShroom.prototype.SunNum=0,
oLilyPad.prototype.SunNum=0,
oSquash.prototype.SunNum=0,
oThreepeater.prototype.SunNum=0,
oTangleKelp.prototype.SunNum=0,
oJalapeno.prototype.SunNum=0,
oSpikeweed.prototype.SunNum=0,
oTorchwood.prototype.SunNum=0,
oTallNut.prototype.SunNum=0,
oSeaShroom.prototype.SunNum=0,
oPlantern.prototype.SunNum=0,
oCactus.prototype.SunNum=0,
oBlover.prototype.SunNum=0,
oSplitPea.prototype.SunNum=0,
oStarfruit.prototype.SunNum=0,
oPumpkinHead.prototype.SunNum=0,
oFlowerPot.prototype.SunNum=0,
oCoffeeBean.prototype.SunNum=0,
oGarlic.prototype.SunNum=0,
oGatlingPea.prototype.SunNum=0,
oGloomShroom.prototype.SunNum=0,
oTwinSunflower.prototype.SunNum=0,
oSpikerock.prototype.SunNum=0




